### ISSUE TITLE
Issues with jQuery 1.6.1

### ISSUE THREAD

**Issue by acusti** [kswedberg/jquery-smooth-scroll#11]
I’ve noticed in testing jQuery 1.6.1 that it seems to no longer be possible to call animate() on either the html or body elements (as in `$('html, body').animate(aniprops);` ). I tested it for scrollTop and width, and for both elements together and separately, and each time I receive this error in the WebKit console: `TypeError: Result of expression 'f.easing[e.animatedProperties[this.prop]]' [undefined] is not a function.`

As a result, I can't get this plugin to work with jQuery 1.6.1 (at least in Firefox and Chrome/Safari). Anyone else had an experience, positive or negative, with this functionality and jQuery 1.6.1?
